site:
  title: Touyr of heroes documentation
  url: https://javiersvg.github.io/tour-of-heroes-docs
  start_page: index::index.adoc
content:
  sources:
  - url: . # common module containing just the main index
    start_path: docs
    branches: HEAD
  - url: https://github.com/javiersvg/tour-of-heroes.wiki.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true